### PR TITLE
25w19a+ version support

### LINKED ISSUE #237: [Resource Pack Error] Resource reload failed (25w19a and higher)
This is shocking but when I attempted to load **Default Dark Mode** in **25w17a or higher** I was met with this unfortunate message below.
Image

from: **25w17a**
25w17a

from: **25w19a**
25w19a

Hey @nebuIr I'm begging you to update the Resource Pack asap! that type of issue shouldn't be happening.

and please bump resource pack format to `63` (1.21.6-pre1)

## Error Message
```
[21:21:38] [Render thread/INFO]: Reloading ResourceManager: vanilla, file/Default-Dark-Mode-Expansion-1.19.0+-2025.5.1-beta.zip, file/Default-Dark-Mode-1.20.2+-2024.6.0.zip
[21:21:38] [Worker-Main-5/INFO]: Found unifont_all_no_pua-16.0.03.hex, loading
[21:21:38] [Worker-Main-6/INFO]: Found unifont_pua-16.0.03.hex, loading
[21:21:38] [Worker-Main-5/INFO]: Found unifont_jp_patch-16.0.03.hex, loading
[21:21:39] [Render thread/ERROR]: Couldn't compile fragment shader (minecraft:core/rendertype_text_intensity): ERROR: 0:8: 'FogStart' : redefinition 
ERROR: 1 compilation errors.  No code generated.
[21:21:39] [Render thread/ERROR]: Couldn't compile pipeline minecraft:pipeline/text_intensity: fragment shader minecraft:core/rendertype_text_intensity was invalid
[21:21:39] [Render thread/ERROR]: Couldn't compile fragment shader (minecraft:core/rendertype_text): ERROR: 0:8: 'FogStart' : redefinition 
ERROR: 1 compilation errors.  No code generated.
[21:21:39] [Render thread/ERROR]: Couldn't compile pipeline minecraft:pipeline/text_polygon_offset: fragment shader minecraft:core/rendertype_text was invalid
[21:21:39] [Render thread/ERROR]: Couldn't compile pipeline minecraft:pipeline/text: fragment shader minecraft:core/rendertype_text was invalid
[21:21:39] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
```

### PR DESCRIPTION
**Pull request by Vi-Tul**
Fixes #237
1.21.6 snapshots have changed a lot in the functionality of the core shaders, especially for shaders using fog.glsl, hence the fix

### CODE REVIEW

**Comment by aricloverEXTRA** [comment]
Hey @ViTulyankin I made a minecraft mod that basically updates the Default Dark Mode resource pack on 1.21.6 SNAPSHOTS!

It updates the pack.mcmeta from **34 (1.21/1.21.1)** to **63 (1.21.6-pre3)**, removing the incompatible resource pack screen.
next, it also includes the changes you've made in this Pull Request!

https://www.curseforge.com/minecraft/mc-mods/default-dark-mode-patcher

This mod may be temporary until NebuIr finally gives it an update. Default Dark Mode feels like it's been abandoned for almost a year.

**Comment by Vi-Tul** [comment]
@aricloverEXTRA, that's great!

**Comment by Vi-Tul** [comment]
Works in 1.21.6 pre3

**Comment by aricloverEXTRA** [comment]
I know, it should work fine in future Minecraft versions until it eventually stops working.

**Comment by nebuIr** [comment]
Thank you! I also went ahead and updated the files using the 1.21.6 source files released today.

Are there any specific reasons for the other changes compared to the source files? In my testing, those changes didn’t seem necessary, so I left them out for now. Please let me know if I'm wrong.
